import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { GlassCard, SectionHeader } from "@/components/dashboard/widgets";
import { Key, Bell, Users, Shield } from "lucide-react";
export function SettingsPage() {
    return (_jsxs("div", { className: "grid grid-cols-1 gap-4 lg:grid-cols-2", children: [_jsxs(GlassCard, { className: "p-5", children: [_jsx(SectionHeader, { title: "Workspace" }), _jsxs("div", { className: "space-y-3 text-sm", children: [_jsxs("div", { children: [_jsx("label", { className: "text-[10px] uppercase tracking-wider text-muted-foreground", children: "Organization" }), _jsx("input", { className: "mt-1 w-full rounded-md border border-border bg-card/50 px-3 py-2 focus:border-primary/60 focus:outline-none", defaultValue: "Acme Security Corp" })] }), _jsxs("div", { children: [_jsx("label", { className: "text-[10px] uppercase tracking-wider text-muted-foreground", children: "Default Risk Threshold" }), _jsxs("select", { className: "mt-1 w-full rounded-md border border-border bg-card/50 px-3 py-2 focus:border-primary/60 focus:outline-none", children: [_jsx("option", { children: "Medium" }), _jsx("option", { children: "High" }), _jsx("option", { children: "Critical" })] })] })] })] }), [
                { Icon: Key, title: "API Keys", desc: "Manage MCP server credentials and provider keys." },
                { Icon: Bell, title: "Notifications", desc: "Configure Slack, email, and PagerDuty routing." },
                { Icon: Users, title: "Team & Roles", desc: "Invite teammates and assign RBAC roles." },
                { Icon: Shield, title: "SSO & SAML", desc: "Enterprise identity provider configuration." },
            ].map(({ Icon, title, desc }) => (_jsxs(GlassCard, { className: "flex items-start gap-4 p-5 transition-colors hover:border-primary/40", children: [_jsx("div", { className: "flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary ring-1 ring-primary/20", children: _jsx(Icon, { className: "h-5 w-5" }) }), _jsxs("div", { className: "flex-1", children: [_jsx("div", { className: "text-sm font-semibold", children: title }), _jsx("p", { className: "mt-0.5 text-xs text-muted-foreground", children: desc })] }), _jsx("button", { type: "button", className: "rounded-md border border-border bg-card/40 px-3 py-1 text-xs hover:bg-card/70", children: "Configure" })] }, title)))] }));
}
