# Generated by Django 6.0.6 on 2026-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("BLOCK_TOOL", "Block Tool"),
                            ("REQUIRE_APPROVAL", "Require Approval"),
                            ("INPUT_VALIDATION", "Input Validation"),
                            ("TOKEN_BUDGET", "Token Budget"),
                        ],
                        max_length=50,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=100)),
                ("hits", models.IntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
    ]
